from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from Proyecto_LeasingMC.fixing_data.preprocess import Preprocess